version: '3.8'

services:
  # Backend API
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=myngo_db
      - DB_USER=root
      - DB_PASSWORD=password
      - JWT_ACCESS_SECRET=your-super-secret-jwt-access-key-here
      - JWT_REFRESH_SECRET=your-refresh-secret-key-here
      - JWT_EXPIRES_IN=24h
      - JWT_REFRESH_EXPIRES_IN=7d
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    depends_on:
      - db
    restart: unless-stopped

  # MySQL Database
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myngo_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data: 